- name: Update packages
  become: true
  apt:
    name: "*"
    state: latest
    force_apt_get: True
    update_cache: yes
  register: update

- name: Add key for docker
  become: true
  apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    keyring: "/etc/apt/keyrings/docker.gpg"

- name: Add docker by url
  become: true
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_facts['distribution_release'] }} stable"
    state: present
    filename: "docker"

- name: Install packages
  become: true
  apt:
    name:
      - git
      - vim
      - curl
      - gnupg
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
      - unzip
      - python3-pip
      - jq

- name: install pip packages
  pip:
    name:
      - flask
      - uwsgi
      - requests
