- name: kubeadm init
  become: true
  ansible.builtin.command: "kubeadm init --pod-network-cidr 10.244.0.0/16"
  when: first_run

- name: kubeadm get join string
  become: true
  ansible.builtin.command: "kubeadm token create  --print-join-command"
  register: join_command

- name: fetch kubeconf
  fetch:
    src: /etc/kubernetes/admin.conf
    dest: admin.conf
    flat: true
  become: true
  when: fetch_config

- name: show join command
  debug:
    msg: "{{ join_command }}"
  when: first_run
