- name: Add key for kubernetes 1.28
  become: true
  apt_key:
    url: "https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key"
    keyring: "/etc/apt/keyrings/kubernetes-1.28.gpg"

- name: Add key for kubernetes 1.29
  become: true
  apt_key:
    url: "https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key"
    keyring: "/etc/apt/keyrings/kubernetes-1.29.gpg"

- name: Add kubernetes 1.28 by url
  become: true
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-1.28.gpg] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /"
    state: present
    filename: "kubernetes"

- name: Add kubernetes 1.29 by url
  become: true
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-1.29.gpg] https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /"
    state: present
    filename: "kubernetes"

- name: Prevent packages from being upgraded
  become: true
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: hold
  with_items:
    - containerd.io
    - kubelet
    - kubeadm
    - kubectl

- name: Install packages
  become: true
  apt:
    allow_downgrade: true
    name:
      - containerd.io=1.6.27-1
      - "kubelet={{ kub_version }}"
      - "kubeadm={{ kub_version }}"
      - "kubectl={{ kub_version }}"

- name: Download cni plugins
  get_url:
    url: "https://github.com/containernetworking/plugins/releases/download/v1.4.0/cni-plugins-linux-amd64-v1.4.0.tgz"
    dest: "/tmp/cni-plugins.tgz"

- name: ensure cni plugins dir
  become: true
  file:
    path: /opt/cni/bin
    state: directory

- name: unpack cni plugins
  become: true
  unarchive:
    src: "/tmp/cni-plugins.tgz"
    remote_src: true
    dest: "/opt/cni/bin"

- name: Add br_netfilter
  become: true
  community.general.modprobe:
    name: br_netfilter
    state: present

- name: ip forwarding
  become: true
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    sysctl_set: true

- name: add containerd config
  become: true
  copy:
    src: config.toml
    dest: /etc/containerd/config.toml
    mode: "0644"
  register: containerd_config_changed

- name: restart containerd
  become: true
  when: containerd_config_changed.changed
  systemd:
    state: restarted
    daemon_reload: true
    name: containerd
